#+title: org-mode-latex-templates
#+author: Atri Hegde

* Preface

Here are some the SETUPFILEs I use when I am writing documents that I will import into a $\LaTeX$.

#+begin_quote
If you are using these templates for real work, check out the sections under [[#reportorg][Report.org]] for more detail on writing in org-mode and exporting to latex.
#+end_quote

* Table of Contents :TOC:
- [[#preface][Preface]]
- [[#simpleorg][simple.org]]
  - [[#example][Example]]
- [[#reportorg][report.org]]
  - [[#example-file][Example file]]
  - [[#header-and-footer][Header and Footer]]
  - [[#tables][Tables]]
  - [[#syntax-highlighting][Syntax highlighting]]
- [[#other-resources][Other resources]]

* [[./simple.org][simple.org]]

** Example

#+begin_src org
,#+title: Big title
,#+subtitle: Subtitle
,#+AUTHOR: Your name
,#+SETUPFILE: ~/.config/doom/latex-templates/report.org

,#+LATEX_HEADER: \fancyhead[C]{Title here}
,#+LATEX_HEADER: \fancyfoot[C]{\thepage}

,#+LATEX: \newpage

Start here...
#+end_src

* [[./report.org][report.org]]

To use it just add the setupfile line.
Setupfile should point to wherever you're =report.org= is on your disk.

** Example file

#+begin_quote
A real example file is in the works and coming soon...
#+end_quote

#+begin_src org
,#+title: Big title
,#+subtitle: Subtitle
,#+AUTHOR: Your name
,#+SETUPFILE: ~/.config/doom/latex-templates/report.org

,#+LATEX_HEADER: \fancyhead[C]{Title here}
,#+LATEX_HEADER: \fancyfoot[C]{\thepage}

,#+LATEX: \newpage

Start here...
#+end_src

** Header and Footer
We are using =fancyhdr= package to achieve this.

** Tables
To get column lines add this to the line above your table.

#+begin_quote
=c|c|c|c= is for a table with four columns, and each aligned to the center.
You can change =c= to =l= or =r= to change this.
Adjust accordingly depending on how many columns you have.
#+end_quote

#+begin_src org
,#+ATTR_LATEX: :align c|c|c|c
#+end_src

** Syntax highlighting

If you are including code blocks in your document and you want it to be pretty than add this to your emacs config.

#+begin_quote
If you are using Doom Emacs it will be in your =config.el=
#+end_quote

#+begin_src emacs-lisp
(setq org-latex-listings 'minted
      org-latex-packages-alist '(("" "minted"))
      org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+end_src


* Other resources
- [[https:olmon.gitlab.io/org-themes][Org HTML Themes Collection]]
